apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-rolebinding
  namespace: jeffw
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: jeffw
roleRef:
  kind: Role
  name: deployment-creator-role
  apiGroup: rbac.authorization.k8s.io