# permissions for end users to edit helxusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helxuser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: builder
    app.kubernetes.io/part-of: builder
    app.kubernetes.io/managed-by: kustomize
  name: helxuser-editor-role
rules:
- apiGroups:
  - helx.renci.org
  resources:
  - helxusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helx.renci.org
  resources:
  - helxusers/status
  verbs:
  - get
