apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: helxapp-pvc-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: builder
    app.kubernetes.io/part-of: builder
    app.kubernetes.io/managed-by: kustomize
  name: helxapp-pvc-manager-rolebinding
  namespace: jeffw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helxapp-pvc-manager-role
subjects:
- kind: ServiceAccount
  name: helxapp-controller-manager
  namespace: jeffw
