apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jeffw
  name: helxapp-pvc-manager-role
rules:
- apiGroups: [""]
  resources: 
  - persistentvolumeclaims
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
