---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helxapp-manager-role
rules:
- apiGroups:
  - helx.renci.org
  resources:
  - helxusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helx.renci.org
  resources:
  - helxusers/finalizers
  verbs:
  - update
- apiGroups:
  - helx.renci.org
  resources:
  - helxusers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helxapp-manager-role
  namespace: jeffw
rules:
- apiGroups:
  - helx.renci.org
  resources:
  - helxapps
  - helxinsts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helx.renci.org
  resources:
  - helxapps/finalizers
  - helxinsts/finalizers
  verbs:
  - update
- apiGroups:
  - helx.renci.org
  resources:
  - helxapps/status
  - helxinsts/status
  verbs:
  - get
  - patch
  - update
