apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: helxapp-controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: builder
    app.kubernetes.io/part-of: builder
    app.kubernetes.io/managed-by: kustomize
  name: helxapp-controller-manager
  namespace: jeffw
